#!/usr/bin/env python3
"""find-open-questions: scan ai_managed zones for `> [!question]` callouts.

Usage: python3 find-open-questions.py <vault_root>

Skips matches inside fenced code blocks (``` or ~~~), which are usually
documentation examples rather than real open questions. Emits one line per
hit:

  <relative_path>\t<line_number>\t<question_text>

Add --report Utility/obsidian-knowledge/reports/open-questions.md to render
Markdown for review, --timestamp for reproducible output, and --apply to write.
Reads ai_managed zones from
<vault_root>/.claude/obsidian-knowledge.yaml; falls back to ['wiki'].
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

from organizer_io import visible_path, write_checked
from pydantic import BaseModel, ConfigDict

try:
    import yaml

    HAS_YAML = True
except ImportError:
    HAS_YAML = False

QUESTION_MARKER = "> [!question]"
SCAN_SKIP_DIR_NAMES = {"_sources", ".trash", "node_modules"}


class QuestionHit(BaseModel):
    model_config = ConfigDict(frozen=True)
    path: str
    line: int
    text: str


def render_question(hit: QuestionHit) -> str:
    # Markdown text, not JSON: preserve backslashes used by math and escapes.
    quoted = hit.text.replace('"', '\\"')
    return f'- [[{hit.path.removesuffix(".md")}]] — line {hit.line} — "{quoted}"\n'


def render_report(before: str | None, hits: tuple[QuestionHit, ...], timestamp: str) -> str:
    if before is None:
        before = (
            "# Open questions\n\n"
            "> Regenerated by vault-organizer. Resolve questions in the source page.\n\n"
            "**Last run:** never\n\n## Scope\n\n"
            "Question callouts in configured AI-managed zones; protected, hidden, "
            "dependency and sync-conflict files excluded.\n\n"
        )
    lines = before.splitlines(keepends=True)
    first_entry = next(
        (i for i, line in enumerate(lines) if re.match(r"^- \[\[.*\]\] — line \d+ — ", line)), len(lines)
    )
    if any(
        line.strip() and not re.match(r"^- \[\[.*\]\] — line \d+ — ", line) for line in lines[first_entry:]
    ):
        raise ValueError("report has content after generated entries; refusing to discard it")
    prefix = "".join(lines[:first_entry])
    prefix, count = re.subn(r"(?m)^\*\*Last run:\*\*[^\r\n]*", lambda _: f"**Last run:** {timestamp}", prefix)
    if count != 1:
        raise ValueError("report must contain exactly one **Last run:** line")
    if not prefix.endswith("\n\n"):
        prefix += "\n" if prefix.endswith("\n") else "\n\n"
    entries = "".join(render_question(hit) for hit in hits)
    return prefix + entries


def load_managed_zones(vault_root: Path) -> list[str]:
    config_path = vault_root / ".claude" / "obsidian-knowledge.yaml"
    if HAS_YAML and config_path.exists():
        with open(config_path) as f:
            cfg = yaml.safe_load(f) or {}
        return cfg.get("ai_managed", ["wiki"])
    return ["wiki"]


def scan_file(path: Path) -> list[tuple[int, str]]:
    """Return [(line_no, question_text)] for each callout outside code fences."""
    hits: list[tuple[int, str]] = []
    in_fence = False
    fence_marker = ""
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
    except OSError:
        return hits

    for i, line in enumerate(lines, start=1):
        stripped = line.lstrip()
        # Track fenced code-block state. Markdown fences start with ``` or ~~~.
        if stripped.startswith(("```", "~~~")):
            marker = stripped[:3]
            if not in_fence:
                in_fence = True
                fence_marker = marker
            elif stripped.startswith(fence_marker):
                in_fence = False
                fence_marker = ""
            continue

        if in_fence:
            continue

        if line.rstrip("\n").startswith(QUESTION_MARKER):
            # Question text is on the next non-blank `> ` line.
            question_text = ""
            for j in range(i, len(lines)):
                next_line = lines[j].rstrip("\n")
                if next_line.startswith("> ") and next_line.strip() != ">":
                    question_text = next_line[2:].strip()
                    break
                if not next_line.startswith(">"):
                    break
            hits.append((i, question_text))

    return hits


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("vault_root", type=Path)
    parser.add_argument("--report", help="render the existing open-questions report (dry run)")
    parser.add_argument("--timestamp", help="timezone-aware ISO timestamp; default: current local time")
    parser.add_argument(
        "--apply", action="store_true", help="write the reviewed report using the verified writer"
    )
    args = parser.parse_args()
    if args.apply and not args.report:
        parser.error("--apply requires --report")
    vault_root = args.vault_root.resolve()
    if not vault_root.is_dir():
        print(f"Error: {vault_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    zones = load_managed_zones(vault_root)
    hits = []
    for zone in zones:
        zone_root = vault_root / zone
        if not zone_root.is_dir():
            continue
        for md in sorted(zone_root.rglob("*.md")):
            rel_parts = md.relative_to(vault_root).parts
            if any(part.startswith(".") or part in SCAN_SKIP_DIR_NAMES for part in rel_parts):
                continue
            rel = md.relative_to(vault_root).as_posix()
            try:
                visible_path(vault_root, rel)
            except ValueError:
                continue
            for line_no, text in scan_file(md):
                hits.append(QuestionHit(path=rel, line=line_no, text=text))
    if not args.report:
        for hit in hits:
            print(f"{hit.path}\t{hit.line}\t{hit.text}")
        return
    try:
        if args.report != "Utility/obsidian-knowledge/reports/open-questions.md":
            raise ValueError("--report must target Utility/obsidian-knowledge/reports/open-questions.md")
        stamp = datetime.fromisoformat(args.timestamp) if args.timestamp else datetime.now().astimezone()
        if stamp.utcoffset() is None:
            raise ValueError("timestamp must include a timezone offset")
        path = visible_path(vault_root, args.report)
        before = path.read_bytes().decode("utf-8") if path.exists() else None
        after = render_report(before, tuple(hits), stamp.isoformat(timespec="seconds"))
        if args.apply:
            write_checked(vault_root, args.report, before, after)
        else:
            sys.stdout.write(after)
    except (ValueError, OSError) as exc:
        parser.exit(1, f"Error: {exc}\n")


if __name__ == "__main__":
    main()
